import smtplib
import os
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv

from config import SMTP_SERVER, SMTP_PORT, SENDER_EMAIL, RECEIVER_EMAIL

load_dotenv()

# We added correlation_id here
def send_alert_email(report_content, correlation_id="Unknown"):
    password = os.getenv("SMTP_PASSWORD")
    
    if not password or not SENDER_EMAIL or not RECEIVER_EMAIL:
        print("\n[!] Email credentials missing in .env or config.py. Skipping email alert.")
        return

    # Now the subject line is unique for every single transaction!
    subject = f"🚨 URGENT: API Failure Root Cause - [{correlation_id}]"
    
    msg = MIMEMultipart()
    msg['From'] = SENDER_EMAIL
    msg['To'] = RECEIVER_EMAIL
    msg['Subject'] = subject

    body = f"Team,\n\nThe AI Correlation Agent has detected a new failure. Below is the automated root cause analysis for transaction {correlation_id}:\n\n"
    body += "-" * 50 + "\n"
    body += report_content
    body += "\n" + "-" * 50 + "\n"
    body += "This is an automated alert generated by the API Failure Correlation Agent."

    msg.attach(MIMEText(body, 'plain', 'utf-8'))

    try:
        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
        server.starttls()
        server.login(SENDER_EMAIL, password)
        server.send_message(msg)
        server.quit()
    except Exception as e:
        print(f"\n[!] Failed to send email for {correlation_id}. Error: {str(e)}")