import smtplib  # The built-in Python tool for sending emails
import os
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv  # Used to securely load hidden passwords

# Import email settings from our config file
from config import SMTP_SERVER, SMTP_PORT, SENDER_EMAIL, RECEIVER_EMAIL

# Load the hidden passwords from the .env file
load_dotenv()

def send_alert_email(report_content, correlation_id="Unknown"):
    # Get the email password securely without writing it directly in the code
    password = os.getenv("SMTP_PASSWORD")
    
    # SAFETY CHECK: Stop and cancel the email if any login details are missing
    if not password or not SENDER_EMAIL or not RECEIVER_EMAIL:
        print("\n[!] Email credentials missing in .env or config.py. Skipping email alert.")
        return

    # Create a unique email subject line using the specific transaction ID
    subject = f"🚨 URGENT: API Failure Root Cause - [{correlation_id}]"
    
    # Build the basic structure of the email (Sender, Receiver, Subject)
    msg = MIMEMultipart()
    msg['From'] = SENDER_EMAIL
    msg['To'] = RECEIVER_EMAIL
    msg['Subject'] = subject

    # Write the actual text message that will go inside the email
    body = f"Team,\n\nThe AI Correlation Agent has detected a new failure. Below is the automated root cause analysis for transaction {correlation_id}:\n\n"
    body += "-" * 50 + "\n"
    body += report_content  # Insert the AI's analysis report here
    body += "\n" + "-" * 50 + "\n"
    body += "This is an automated alert generated by the API Failure Correlation Agent."

    # Attach our text message to the email structure we built earlier
    msg.attach(MIMEText(body, 'plain', 'utf-8'))

    # Try to send the email, but catch any errors so the whole program doesn't crash
    try:
        # Connect to the email provider's server (like Gmail or Outlook)
        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
        server.starttls()  # Upgrade the connection to be secure and encrypted
        
        # Log in and send the message
        server.login(SENDER_EMAIL, password)
        server.send_message(msg)
        
        # Close the connection when finished
        server.quit()
    except Exception as e:
        # If the internet is down or login fails, print a warning instead of crashing
        print(f"\n[!] Failed to send email for {correlation_id}. Error: {str(e)}")