import smtplib
import os
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv

# Import the settings from your config file
from config import SMTP_SERVER, SMTP_PORT, SENDER_EMAIL, RECEIVER_EMAIL

load_dotenv()

def send_alert_email(report_content):
    password = os.getenv("SMTP_PASSWORD")
    
    # Safety check
    if not password or not SENDER_EMAIL or not RECEIVER_EMAIL:
        print("\n[!] Email credentials missing in .env or config.py. Skipping email alert.")
        return

    subject = "🚨 URGENT: API Failure Root Cause Analysis"
    
    msg = MIMEMultipart()
    msg['From'] = SENDER_EMAIL
    msg['To'] = RECEIVER_EMAIL
    msg['Subject'] = subject

    # Create the email body with your generated report
    body = f"Team,\n\nThe AI Correlation Agent has detected new failures. Below is the automated root cause analysis:\n\n"
    body += "-" * 50 + "\n"
    body += report_content
    body += "\n" + "-" * 50 + "\n"
    body += "This is an automated alert generated by the API Failure Correlation Agent."

    msg.attach(MIMEText(body, 'plain', 'utf-8'))

    try:
        print("\nSending email alert to team...", end=" ", flush=True)
        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
        server.starttls() # Secure the connection
        server.login(SENDER_EMAIL, password)
        server.send_message(msg)
        server.quit()
        print("Sent successfully! ✉️")
    except Exception as e:
        print(f"\n[!] Failed to send email. Error: {str(e)}")